spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
  thymeleaf:
    cache: false
  messages:
    encoding: UTF-8
    basename: message_zh_CN
server:
  port: 9000
